### ISSUE TITLE
.htaccess file should not be in this repository

### ISSUE THREAD

**Issue by IgorPodlawski** [software-things/form-carter#12]
IMO .htaccess file shouldn't be here. Form Carter can be deployed on different environments and .htaccess is valid only on Apache (and on some other webservers implementing this file).

**Comment by kamiljedrkiewicz** [comment]
IMO there is no need to remove this file, because it is ignored by **nginx** and in case of **apache** it becomes useful.

**Comment by IgorPodlawski** [comment]
Let's move this discussion to the PR #13.
