### ISSUE TITLE
Default message should come from config.php

### ISSUE THREAD

**Issue by IgorPodlawski** [software-things/form-carter#15]
## Problem description
[Here](https://github.com/software-things/form-carter/blob/master/index.php#L122) we have default message in polish – used when _subject is not provided:

`'Wiadomość z serwisu ' . ($_SERVER['HTTP_HOST']` 

This could be a problem while using FormCarter in other languages. 'Wiadomość z serwisu' means 'Message from website' and this default string should be provided in config.php file.

**Comment by kamiljedrkiewicz** [comment]
I' m working on that issue :)
