### ISSUE TITLE
Default_title error

### ISSUE THREAD

**Issue by tomaszkiewiczanna** [software-things/form-carter#18]
default_title in config file shouldn't be in an array

Occurrence:  Message comes with a subject 'Arraydefault_title'
![Zrzut ekranu 2019-11-8 o 10 59 53](https://user-images.githubusercontent.com/26789919/68467684-f0295c80-0216-11ea-8911-bdea7f07a533.png)

**Comment by IgorPodlawski** [comment]
Could you please describe this issue more broadly?
